pub use ::html::content::{
    Address,
    Address as address,
    Footer,
    Footer as footer,
    Header,
    Header as header,
    Heading1,
    Heading1 as h1,
    Heading2,
    Heading2 as h2,
    Heading3,
    Heading3 as h3,
    Heading4,
    Heading4 as h4,
    Heading5,
    Heading5 as h5,
    Heading6,
    Heading6 as h6,
    Main,
    Main as main,
};
pub use ::html::inline_text::{
    Abbreviation,
    Abbreviation as abbr,
    Anchor,
    Anchor as a,
    Bold,
    Bold as b,
    Italic,
    Italic as i,
    LineBreak,
    LineBreak as br,
    Span,
    Span as span,
    Time,
    Time as time,
};
pub use ::html::interactive::{
    Details,
    Details as details,
    Summary,
    Summary as summary,
};
pub use ::html::metadata::{
    Head,
    Head as head,
    Link,
    Link as link,
    Meta,
    Meta as meta,
    Title,
    Title as title,
};
pub use ::html::root::{
    Body,
    Body as body,
    Html,
    Html as html,
};
pub use ::html::text_content::{
    Division,
    Division as div,
    ListItem,
    ListItem as li,
    OrderedList,
    OrderedList as ol,
    Paragraph,
    Paragraph as p,
    UnorderedList,
    UnorderedList as ul,
};
