use crate::{entries, entry, html, page::BuildContext};

entries!(
    // Page 1
    [
        // 1-10
        ["abstract"] => ["basal"],
        ["academic"] => ["pantalisikan"],
        ["action"] => ["gawa", "bilos"],
        ["activity"] => ["kabilusan"],
        ["address"] => ["padalahan"],
        ["adviser"] => ["tagapayo"],
        ["again"] => ["muli"],
        ["agenda"] => ["tikmaan"],
        ["airman"] => ["manlilipad"],
        ["album"] => ["tipunan"],
        // 11-20
        ["always"] => ["lagi"],
        ["amount"] => ["daghan"],
        ["analogy"] => ["palasurian"],
        ["analysis"] => ["suri"],
        ["announcement"] => ["pabatid"],
        ["arc"] => ["bantok"],
        ["area"<g:"in general">] => ["lawak"],
        ["area"<g:"specified">] => ["dawak"],
        ["around"] => ["palibot"],
        ["arrangement"] => ["ayos"],
        // 21-30
        ["artificial"] => ["gawa-gawa"],
        ["assistant"] => ["kawaksi"],
        ["atmosphere"] => ["kaanginan"],
        ["attendance"] => ["sadalo"],
        ["autobiography"] => ["sariltalambuhay"],
        ["average"] => ["balasak"],
        ["axis"] => ["taluhog"],
        ["base"] => ["takad"],
        ["big", "great", "grand"] => ["malaki", "dako"],
        ["bilingual"] => ["dalwikain"],
        // 31-39
        ["biologi"] => ["haynayan"],
        ["body"<g:"inorganic">] => ["lawas"<l:Hlg>],
        ["booklet"] => ["muntaklat"],
        ["bulletin board"] => ["paskilan"],
        ["by means of"] => ["sagitan ng"],
        ["campus"] => ["kampusan"],
        ["candidate"] => ["halangad"],
        ["canteen"] => ["manganan"<l:Kpn>],
        ["capacity"] => ["lulan"],
    ],
    // Page 2
    [
        // 40
        ["car"] => ["batlag"],
        // 41-50
        ["cash"<g:"money on hand">] => ["salaping-hawak"],
        ["cashier"] => ["ingatsalapi"],
        ["center"] => ["lunduyan"],
        ["ceremony"] => ["galian"],
        ["certain"] => ["tiyak"],
        ["change"] => ["baylo"<l:Bis>],
        ["chaplain"] => ["kapelyan"],
        ["chart"] => ["taltaguhit"],
        ["chemistry"] => ["kapnayan"],
        ["circular letter"] => ["palibot-sulat"],
        // 51-60
        ["civilization"] => ["kabihasnan"],
        ["clearance"] => ["hisagutin"],
        ["clinic"] => ["gamutan"],
        ["closed"] => ["pinid"],
        ["coldness"] => ["lamig"],
        ["cold season"] => ["taglamig"],
        ["college", "institute"] => ["dalubhasaan"],
        ["committee"] => ["lupon"],
        ["communication"] => ["talamitam"],
        ["companion"] => ["abay"],
        // 61-70
        ["complete"] => ["ganap"],
        ["composite"] => ["lakip"],
        ["compute"] => ["tuos"],
        ["concavity"] => ["lukong"],
        ["concept"] => ["dalumat"],
        ["condense"] => ["kintay"],
        ["conscious mind"] => ["malay"],
        ["consistently interrelated"] => ["maugnayin"],
        ["consultant"] => ["kasangguni"],
        ["convexity"] => ["lukob"],
        // 71-80
        ["copyright"] => ["karapatang-akda"],
        ["correct"] => ["wasto"],
        ["create"] => ["likha"],
        ["creative"] => ["malikhain"],
        ["cultural"] => ["pangkalinangan"],
        ["culture"] => ["kalinangan"],
        ["curved"] => ["kilo"],
        ["cylinder"] => ["bumbong"],
        ["cylindrical"] => ["binumbong"],
        ["date"] => ["taburaw"],
        // 81-82
        ["dean"] => ["dalubpuno"],
        ["decrease"] => ["bawas"],
    ],
    // Page 3
    [
        // 83-90
        ["definition"] => ["katuringan"],
        ["delivery"] => ["hatid"],
        ["dense"] => ["siksik"],
        ["design"] => ["antang"<l:Mar>],
        ["development"] => ["saunlad"],
        ["deviation"] => ["lihis"],
        ["dictionary"] => ["talatinigan"],
        ["digestion"] => ["satunaw"],
        // 91-100
        ["direction"] => ["tungo"],
        ["director"] => ["patnugot"],
        ["directory"<q:r#gen>] => ["talahanapan"],
        ["disconnection"] => ["tanggal"],
        ["distance"] => ["agwat"],
        ["doctor"<q:PhD>] => ["pantas"],
        ["dormitory"] => ["panuluyan"],
        ["draft"] => ["waki"],
        ["duration"] => ["lawig"],
        ["earth"] => ["duta"<l:Bis>],
        // 101-110
        ["edge"] => ["gilid"],
        ["eucation"<g:"as a system">] => ["paturuan"],
        ["effect"] => ["bisa"],
        ["electricity"] => ["dagitab"],
        ["elevator"] => ["sigtas"],
        ["emeritus"] => ["higitlingkod"],
        ["employee"] => ["kawani"],
        ["encyclopedia"] => ["santalaalaman"],
        ["endorsement"] => ["satukoy"],
        ["energy"] => ["kusog"<l:Bis>],
        // 111-120
        ["engineer"] => ["agsikap"],
        ["environment"] => ["kapaligiran"],
        ["epic"] => ["darangan"<l:Mar>],
        ["erase"] => ["payi"],
        ["escalator"] => ["sigdan"],
        ["estimate"] => ["taya"],
        ["ethics"] => ["palasalan"],
        ["evaluation form"] => ["talahalgahan"],
        ["even"<q:Math>] => ["tukol"],
        ["exact"] => ["singkad"],
        // 121-125
        ["excess"] => ["labaw"<l:Hlg>, "labis"],
        ["exercise"<g:"physical">] => ["sabanat"],
        ["experiment"] => ["tilaw"<l:Bis>],
        ["extreme"] => ["sukdulan"],
        ["facilities"] => ["kaluwagan"],
    ],
    // Page 4
    [
        // 126-130
        ["faculty"<q:Ed>] => ["kaguruan"],
        ["fmily"] => ["angkan"],
        ["fee"] => ["bayad"],
        ["field"] => ["larang"],
        ["figure"] => ["laraw"],
        // 131-140
        ["filling cabinet"] => ["salansanan"],
        ["firmess"] => ["katatagan"],
        ["flight"] => ["lipad"],
        ["focus"] => ["tingob"<l:Hlg>],
        ["folder"] => ["ipitan"],
        ["force"] => ["isig"<l:MatTag>],
        ["form"] => ["anyo", "anyuan"],
        ["formal"] => ["maanyo"],
        ["foundation"] => ["takaran"],
        ["gether together"] => ["lagom"],
        // 141-150
        ["general"] => ["lahatan"],
        ["glossary"] => ["talahulugan"],
        ["graduate school"] => ["dalubhasikan"],
        ["grain"] => ["butil"],
        ["grandstand"] => ["dakmasiran"],
        ["granular"] => ["malabutil"],
        ["gravity"] => ["dagsin"<l:Ilk>],
        ["group"] => ["lipon"],
        ["hall"] => ["bulwagan"],
        ["hidden"] => ["kubli"],
        // 151-160
        ["husband"] => ["bana"<l:Bis>],
        ["hymm"] => ["santinig"],
        ["idea"] => ["kaisipan"],
        ["identification"<a:"I.D.">] => ["pangilala"],
        ["imperfect"<q:Math>] => ["balhag"],
        ["imperfect"<q:r#gen>] => ["di-himpit"],
        ["increase"] => ["dagdag"],
        ["increase of speed"] => ["dasig"<l:Bis, l:Bkl>],
        ["indigestion"] => ["di-satunaw"],
        ["indirect measurement"] => ["sukod"],
        // 161-168
        ["infra-"<g:"comb. form">] => ["sulud-"<l:Bis>],
        ["instant"] => ["dagli"],
        ["intention"] => ["sadya"],
        ["intermission"] => ["panalingit"],
        ["invocation"] => ["panawagan"],
        ["involvement"] => ["sadawit"],
        ["irrigation"] => ["patubig"],
        ["jargon"] => ["wiwika"],
    ],
    // Page 5
    [
        // 169-170
        ["jeopardy"] => ["sanganib"],
        ["Junior"<a:"Jr.">] => ["Anak"<a:"Ak.">],
        // 171-180
        ["justice"] => ["katarungan"],
        ["juvenile"] => ["kabataan"],
        ["kilogram"] => ["libogramo"],
        ["kilometer"] => ["libometro"],
        ["kin"] => ["hinlog", "kaanak"],
        ["kind"] => ["uri"],
        ["leader"] => ["pamuno"],
        ["lecture"] => ["panayam"],
        ["lesson"] => ["aral"],
        ["life"] => ["buhay"],
        // 181-190
        ["light"<g:"optics">] => ["suga"<l:Hlg>],
        ["limit"] => ["takda"],
        ["lobby"] => ["lisawan"],
        ["log book"<g:"attendance">] => ["taladaluhan"],
        ["lore"] => ["alamin"],
        ["major"<q:Ed>] => ["kalakhan"],
        ["majority"] => ["karamihan"],
        ["masses"] => ["santao"],
        ["master"<g:"degree">] => ["paham"],
        ["mathematics"] => ["sipnayan"],
        // 191-200
        ["measuring scale"] => ["sukatan"],
        ["memorandum"] => ["paandam"],
        ["messenger"] => ["tagahatid"],
        ["Metro-Manila"] => ["Dak-Maynila"],
        ["microphone"] => ["miktinig"],
        ["middle"] => ["gitna"],
        ["mimeograph"] => ["limwad"],
        ["mind"] => ["isip"],
        ["minor"<q:Ed>] => ["kalit-an"],
        ["minor"<g:"Gen.">] => ["maliit"],
        // 201-210
        ["minutes"<g:"of a meeting">] => ["katitikan"],
        ["more than"] => ["higit sa"],
        ["motion"] => ["kilos"],
        ["movement"] => ["kilusan"],
        ["multiple"] => ["lambal"],
        ["name"<q:Ling>] => ["ngalan"],
        ["narrate"] => ["saysay"],
        ["natural"] => ["likas"],
        ["nerve"] => ["dagandam"],
        ["next"] => ["sunod"],
        // 211
        ["none"<a:"zero">] => ["awan"<l:Ilk>],
    ],
    // Page 6
    [
        // 212-220
        ["notebook"] => ["aklat-talaan"],
        ["novel"] => ["kathambuhay"],
        ["nucleus"] => ["butod"],
        ["number"] => ["bilang"],
        ["observation"] => ["masid"],
        ["obstacle"] => ["hadlang"],
        ["odd"<q:Math>] => ["gansal"],
        ["official"] => ["tungukulanin"],
        ["one hundred thousand"] => ["yuta"],
        // 221-230
        ["organization"] => ["katatagan"],
        ["organ"] => ["tatag"],
        ["orientation"] => ["satungo"],
        ["orthography"] => ["palatitikan"],
        ["out of the regular"] => ["liwas"],
        ["outstanding"] => ["katangi-tangi"],
        ["park"] => ["liwasan"],
        ["parliament"] => ["batasan"],
        ["part"] => ["hati", "bahagi"],
        ["particle"] => ["tipik"],
        // 231-240
        ["patent"] => ["karapatang-tuklas"],
        ["permission"] => ["tulot"],
        ["philosophy"] => ["batnayan"],
        ["physics"] => ["sugnayan"],
        ["pierce"] => ["tuhog"],
        ["place"] => ["lunan"],
        ["population"] => ["santauhan"],
        ["positive"] => ["tahas"],
        ["practice"] => ["sanay"],
        ["press release"] => ["ngalandakan"],
        // 241-250
        ["process"] => ["saayos"],
        ["profession"] => ["panungkulan"],
        ["professor"] => ["dalubguro"],
        ["programme"] => ["talatuntunan"],
        ["progress"] => ["unlad"],
        ["proper"] => ["tumpak", "angkop"],
        ["prosody"] => ["palabigkasan"],
        ["prosperity"] => ["kaniguhan"],
        ["psychology"] => ["dalub-isipan"],
        ["publication"] => ["lathalain"],
        // 251-254
        ["radio"] => ["diglap"],
        ["real"] => ["tunay"],
        ["receipt"] => ["dawat"],
        ["record"] => ["tala"],
    ],
    // Page 7
    [
        // 255-260
        ["reduction"] => ["maliw"],
        ["referendum"] => ["pagtutukoy"],
        ["region"] => ["danay"<l:Bis>],
        ["related"] => ["kaugnay"],
        ["religion"] => ["agamahan"<l:Mar>],
        ["remainder"] => ["labi"],
        // 261-270
        ["report"] => ["ulat"],
        ["repository"] => ["simpanan"],
        ["repulsion"] => ["sikway"<l:Hlg>],
        ["result"] => ["bunga", "kinalabasan"],
        ["retail"] => ["tingi"],
        ["return"] => ["balik"],
        ["review"] => ["balik-aral"],
        ["revision"] => ["mulinyos"],
        ["revolution"<q:Mech>] => ["ikit"],
        ["revolve"] => ["ligid"],
        // 271-280
        ["rotation"] => ["inog"],
        ["rural"] => ["pangkabukiran", "kabukiranin"],
        ["scholar"] => ["paaral"],
        ["science"] => ["agham"],
        ["science museum"] => ["tanyagang agham"],
        ["score"] => ["lubig"],
        ["seedling"] => ["binhi"],
        ["sediment"] => ["tining"],
        ["semester"] => ["hatintaon"],
        ["seminar"] => ["binhisipan"],
        // 281-290
        ["Senior"<a:"Sr.">] => ["Ama"<a:"Am.">],
        ["sense"] => ["damdam"],
        ["shape"] => ["hugis"],
        ["sign"] => ["tanda"],
        ["similarity"] => ["hawig"],
        ["small things"] => ["mikmik"],
        ["social sciences"] => ["ulnayan"],
        ["society"<g:"in general">] => ["ulnong"<l:Ilk>],
        ["solid"] => ["siksin"],
        ["solve"<g:"a problem">] => ["lutas"],
        // 291-296
        ["source"] => ["mula"],
        ["sowing"] => ["hasik"],
        ["special"] => ["tangi"],
        ["speed"] => ["bilis"],
        ["sports"] => ["sanlaruan"],
        ["spread"] => ["latag"],
    ],
    // Page 8
    [
        // 297-300
        ["square"] => ["parisukat"],
        ["star"] => ["tala"],
        ["steel"] => ["paslip"<l:Ilk>],
        ["stoppage"] => ["tigil"],
        // 301-310
        ["straight"] => ["tuwid"],
        ["student"] => ["mag-aaral"],
        ["subconscious mind"] => ["kubmalay"],
        ["substance"] => ["sangkap"],
        ["summary"] => ["buod"],
        ["surface"] => ["dayag"],
        ["surname"] => ["alangkan"],
        ["switch"] => ["kabtol"],
        ["syntax"] => ["palaugnayan"],
        ["system"] => ["kaayusan"],
        // 311-320
        ["table of contents"] => ["talalamanan"],
        ["tactics"] => ["paagi"<l:Bis>],
        ["technical"] => ["aghimuin"],
        ["technology"] => ["aghimuan"],
        ["telephone"] => ["hatinig"],
        ["television"] => ["tanlap"],
        ["term"] => ["tawag"],
        ["term paper"] => ["sultaning"],
        ["thermometer"] => ["initsukat"],
        ["thermostat"] => ["initsupil"],
        // 321-330
        ["thesis"] => ["tikha"],
        ["thought"] => ["isipin"],
        ["trust"] => ["sikad"],
        ["time"] => ["takna"<l:Bis>],
        ["tone"] => ["linig"],
        ["top"] => ["tuktok"],
        ["track"] => ["tunton"],
        ["training"] => ["pasanayan"],
        ["treasurer"] => ["ingatyaman"],
        ["trunk"] => ["puno"],
        // 331-339
        ["trustee"] => ["katiwala"],
        ["typewriter"] => ["limbitan"],
        ["typewriting paper"] => ["papel-limbitan"],
        ["typist"] => ["manlilimbit"],
        ["university"] => ["pamantasan"],
        ["unnatural"] => ["dilikas"],
        ["unravel"] => ["nisnis"],
        ["urban"] => ["panlunsod"],
        ["vapor"] => ["singaw"],
    ],
    // Page 9
    [
        // 340
        ["velocity"] => ["tulin"],
        // 341-350
        ["vice-president"] => ["puli-pangulo"],
        ["vocabulary"] => ["talasalitaan"],
        ["vocational"] => ["hanapbuhayin"],
        ["voice"] => ["tinig"],
        ["volume"] => ["buok"],
        ["voluntary"] => ["kusa"],
        ["vote"<g:"in an election">] => ["halal"],
        ["whole"] => ["buo"],
        ["world"] => ["daigdig"],
        ["writings"] => ["panulatan"],
    ],
);

#[inline]
pub fn karaniwang_salita(mut context: BuildContext<'_>) {
    let mut entries = entry::build_entries_noncollapsible(
        ENTRIES,
        0,
        0,
        html!(h1 "Mga Karaniwang Salitang Pang-agham").build(),
    );
    entries.set_style(Some("counter-reset: vocabulary;".to_string()));
    context.builder_mut().push(entries);
}
