use crate::entry::definitions;

definitions!(
    // Page 12
    [
        // 460
        ["absolute value"] => ["halgang wagas"],
        // 461-470
        ["abstract number"] => ["bilang na basal"],
        ["add"] => ["magdagdag"],
        ["addend"] => ["panagdag"],
        ["adition"] => ["palaragdagan"],
        ["arithmetic"] => ["bilnuran"<ety:blend<"bilang"><"sunuran">>],
        ["augend"] => ["dagdagin"],
        ["base"] => ["takad"],
        ["binomial"] => ["duhakay"],
        ["cardinal number"] => ["bilang na paulat"],
        ["carry"] => ["dalhin"],
        // 471-480
        [r#""carry five""#] => [r#""dala lima""#],
        ["classification of numbers"] => ["palaurian ng mga bilang"],
        ["clock arithmetic"] => ["bilnurang taknain"],
        ["closure"] => ["kapiniran"],
        ["complex fraction"] => ["hugnaying hatimbilang"],
        ["composite number"] => ["bilang na pinaglakip"],
        ["compound fraction"] => ["langkaping hatimbilang"],
        ["consecutive integer"] => ["kasunod na buumbilang"],
        ["counting numbers"] => ["bilang na panalatag"],
        ["cross multiplication"] => ["laktawang palaramihan"],
        // 481-488
        ["cross products"] => ["mga laktawang bunga"],
        ["decade"<t:"ten of anything">] => ["sinampu"],
        ["decade"<t:"ten years">] => ["pultaon"],
        ["decimal fraction"] => ["sampuing hatimbilang"],
        ["decimal"] => ["sampuan"],
        ["decimal point"] => ["tuldok-sampuan"],
        ["decimal system"] => ["panampuan"],
        ["deduct"] => ["awasin"],
    ],
    // Page 13
    [
        // 489-490
        ["denominator"] => ["pamahagi"],
        ["difference"] => ["kaibhan"],
        // 491-500
        ["digit"] => ["tambilang"],
        ["divide"] => ["maghati"],
        ["divided by"] => ["hatiin sa"],
        ["dividend"] => ["hatiin"],
        ["divisible"] => ["mahahati"],
        ["divisibility"] => ["pagkahatiin"],
        ["division"] => ["palahatian"],
        ["divisor"] => ["pahati"],
        ["double"] => ["dinalawa"],
        ["enumerate"] => ["sabilangin"],
        // 501-510
        ["expanded form"] => ["pinaraming anyo"],
        ["exponent"] => ["paulit"],
        ["factor"] => ["kabuo"],
        ["four fundamental operations"] => ["apat na batayang sakilos"],
        ["fraction"] => ["hatimbilang"],
        ["function"] => ["kabisa"],
        ["Hindu-Arabic numbers"] => ["pamilang na Hindu-Arabe"],
        ["improper fraction"] => ["diangkop na hatimbilang"],
        ["integer"] => ["buumbilang"],
        ["irrational number"] => ["bilang na ditagwayin"],
        // 511-520
        ["least common denominator"<alt:"LCD">] => ["pinakamaliit na lahatang pamahagi"<alt:"PLP">],
        ["least common multiple"<alt:"LCM">] => ["pinakamaliit na lahatang kaparami"<alt:"PLK">],
        ["line segment"] => ["putol na guhit"],
        ["lowest term"] => ["pinakamababang takay"],
        ["mean"] => ["tamtaman"],
        ["measurement"] => ["sukat"],
        ["minuend"] => ["bawasin"],
        ["minus"] => ["bawas"],
        ["mixed fraction"] => ["haluang hatimbilang"],
        ["monomial"] => ["isakay"<ety:from<"isang takay">>],
        // 521-528
        ["multiple"<pos:adj>] => ["dinami", "maramihan"],
        ["multiple"<pos:n>] => ["kaparami"],
        ["multinomial"] => ["maramikay"],
        ["multiplicand"] => ["damihin"],
        ["multiplication"] => ["palaramihan"],
        ["multiplication table"] => ["talay ng palaramihan"],
        ["multiplier"] => ["parami"],
        ["multiply"] => ["magparami"],
    ],
    // Page 14
    [
        // 529-530
        ["natural number"] => ["bilang na likas"],
        ["negative sign"] => ["tandang baling"],
        // 531-540
        ["number"] => ["bilang"],
        ["numbering"] => ["kabilangan", "pagbibilang"],
        ["numeral"] => ["pambilang"],
        ["numerology"] => ["palabilangan"],
        ["numerator"] => ["panakda"],
        ["one half"] => ["kalahati"],
        ["order"] => ["panunuran"],
        ["ordinal number"] => ["bilang na panunod"],
        ["percent"] => ["bahagdan"],
        ["plus"] => ["dagdag"],
        // 541-550
        ["polynomial form"] => ["damikaying anyo"],
        ["point"<alt:".">] => ["tuldok"],
        ["positive sign"] => ["tandang tahas"],
        ["power"] => ["lambal"],
        ["problem"] => ["lutasin"],
        ["proper fraction"] => ["angkop na hatimbilang"],
        ["proportion"] => ["hagway"<ety:inh<MatTag:- >>],
        ["quantity to be found"] => ["hanapin"],
        ["quotient"] => ["kahatian"],
        ["ratio"] => ["tagway"<ety:inh<MatTag:- >>],
        // 551-560
        ["rational number"] => ["bilang na tagwayin"],
        ["reciprocal"] => ["kabaligtad"],
        ["remainder theorem"] => ["hunain ng labi"],
        ["Roman numerals"] => ["pamilang Romano"],
        ["rounding off"] => ["pagbilog"],
        ["short cut"] => ["laktod"<ety:bor<Hlg:- >>],
        ["sign"] => ["tanda", "pananda"],
        ["similar fractions"] => ["hawig na hatimbilang"],
        ["simplest form or term"] => ["pinakapayak na takay"],
        ["simplify"<pos:v>] => ["payakin"],
        // 561-570
        ["single"] => ["inisa"],
        ["solvable"] => ["malulutas"],
        ["subtract"] => ["magbawas"],
        ["subtraction"] => ["palabawasan"],
        ["subtrahend"] => ["pamawas"],
        ["sum"] => ["dagup"<ety:bor<Ilk:- >>],
        ["term"] => ["takay"],
        ["therefore"] => ["kung gayon"],
        ["times"] => ["maka"<lalt:"x">],
        ["total"] => ["kabuuan"],
        // 571
        ["transpose"<pos:v>] => ["ilipat"],
    ],
    // Page 15
    [
        // 572-577
        ["transposition"<pos:n>] => ["salipat"],
        ["trinomial"] => ["talukay"],
        ["unique"] => ["nag-iisa"],
        ["unknown"] => ["di-alam"],
        ["zero"] => ["awan", "sero"],
        ["zero exponent"] => ["awan na paulit"],
    ],
);
