use crate::entries;

entries!(
    // Page 9
    [
        // 351-360
        ["addition property"] => ["kaangkinang paragdag"],
        ["additive inverse"] => ["dagdaging kabaligtaran"],
        ["algebra of sets"] => ["panandaan ng tangkas"],
        ["and so on…"] => ["at pagayon…"],
        ["any set"] => ["anumang tanglas"],
        ["A prime"<a:"A'">] => ["A kudlit"],
        ["a set"] => ["isang tangkas"],
        ["associative"] => ["ugnayin"],
        ["associative law"] => ["ugnaying batas"],
        ["associativity"] => ["kaugnayin"],
        // 361-370
        ["belongs to"] => ["ay nauukol sa"],
        ["can be placed into one-to-one correspondence"] => ["maisusungkad"<a:"maisasatugon nang isa-sa-isa">],
        ["closure property"] => ["kaangkinang pinid"],
        ["collection"] => ["katipunan"],
        ["commutative"] => ["palitin"],
        ["commutativity"] => ["pagkapalitin"],
        ["commutative law"] => ["paliting batas"],
        ["complement of a set"] => ["kapuno ng isang tangkas"],
        ["coset"] => ["katangkas"],
        ["definite set"] => ["tangkas na turing"],
        // 371-376
        ["countable"] => ["mabibilang"],
        ["derived set"] => ["hangong tangkas"],
        ["diagram"] => ["guhitin"],
        ["difference of sets"] => ["kaibhan ng tangkas"],
        ["disjoint sets"] => ["diugnay na tangkas"],
        ["distributive"] => ["bahagihin"],
    ],
    // Page 10
    [
        // 377-380
        ["distributivity"] => ["pagkabahagihin"],
        ["domain"] => ["saklaw"],
        ["element"] => ["mulhagi"<e:"mulaang bahagi">],
        ["element of a set"] => ["mulhagi ng isang tangkas"],
        // 381-390
        ["empty"<a:"null"> "set"] => ["walang-lamang tangkas"],
        ["equal to"] => ["tumbas sa"],
        ["equivalence"] => ["pagkakahalga"],
        ["equivalent"] => ["kahalga"],
        ["equivalent set"] => ["kahalgang tangkas"],
        ["equivalent sets"] => ["mga kahalgang tangkas", "magkakahalgang tangkas"],
        ["false statement"] => ["di-tunay na saad"],
        ["finite set"] => ["hangganing tanglas"],
        ["finite number of elements"] => ["hangganing bilang ng mga mulhagi"],
        ["given a set A"] => ["ibinigay ang tangkas A"],
        // 391-400
        ["greater than"] => ["higit sa"],
        ["Hausdorf space"] => ["walaying talangkas"],
        ["hence"] => ["kaya nga"],
        ["identical elements"] => ["mga kasiyangang mulhagi"],
        ["identity element"] => ["kasiyangang mulhagi"],
        ["if and only if"<a:"iff">] => ["kung at kung lamang"<a:"kkl">],
        ["improper subset"] => ["di-angkop na kubtangkas"],
        ["indefinite set"] => ["tangkas na dituring"],
        ["inequality"] => ["dikatumbasan"],
        ["infinite set"] => ["awanganintangkas"],
        // 401-410
        ["infinite number of elements"] => ["awanganing bilang ng mga mulhagi"],
        ["intersection"] => ["bagtas"],
        ["intersection of two sets"] => ["bagtas ng dalawang tangkas"],
        ["inverse element"] => ["kabaligtarang mulhagi"],
        ["inverse operation"] => ["baligtaring sakilos"],
        ["is a subset of"] => ["ay kubtangkas ng"],
        ["is equivalent to"<g:"set">] => ["ay kahalga ng"<g:"tangkas">],
        ["less than"] => ["kubos sa"],
        ["member"] => ["kabilang"],
        ["member of a set"] => ["kabilang ng isang tangkas"],
        // 411-415
        ["metric space"] => ["sukating talangkas"],
        ["multiplication property"] => ["kaangkinang parami"],
        ["multiplication inverse"] => ["paramihing kabaligtaran"],
        ["not equal to"] => ["di-tumbas sa"],
        ["not less than"] => ["dikubos sa"],
    ],
    // Page 11
    [
        // 416-420
        ["number line"] => ["guhitbilang"],
        ["one-to-one correspondence"] => ["sungkad"<l:MatTag>],
        ["open phrase"] => ["bukas na parirala"],
        ["open sentence"] => ["bukas na pangungusap"],
        ["operation"] => ["sakilos"],
        // 421-430
        ["operation on sets"] => ["mga sakilos sa mga tangkas"],
        ["operator"] => ["pakilos"],
        ["ordered pair"] => ["kapid na ayos"],
        ["pair"] => ["kapid"<l:Bis>],
        ["permissible values"] => ["maaaring halga"],
        ["proper subset"] => ["angkop na kubtangkas"],
        ["property"] => ["kaangkinan"],
        ["range"] => ["abot"],
        ["reflexive property"] => ["kaangkinang pabalik"],
        ["reflexivity"] => ["pagkapabalik"],
        // 431-440
        ["replacemenet set"] => ["pamalit na tangkas"],
        ["roster"<a:"tabulation"> "method"] => ["pamamaraang panalatag"],
        ["rule"<a:"defining property"> "method"] => ["pamamaraang panturing"],
        ["set"] => ["tangkas"],
        ["set equality"] => ["katumbasan ng tangkas"],
        ["set notation"] => ["halat ng tangkas"],
        ["set of numbers"] => ["tangkas ng mga bilang"],
        ["set of positive integers"] => ["tangkas ng mga tahas na buumbilang"],
        ["shade the circle"] => ["liliman ang bilog"],
        ["solution set"] => ["tangkas ng kalutasan"],
        // 441-450
        ["statement"] => ["saad"],
        ["subset"] => ["kubtangkas"],
        ["superset"] => ["higtangkas"],
        ["symbol"] => ["sagisag"],
        ["symmetric property"] => ["kaaangkinang parianyuin"],
        ["the entire"<a:"whole"> "set"] => ["ang buong tangkas"],
        ["the set"] => ["ang tangkas"],
        ["topological set"] => ["lunaning talangkas"],
        ["totality"] => ["sangkabuuan"],
        ["transitive property"] => ["kaangkinang palipat"],
        // 451-453
        ["transitivity"] => ["pagkapalipat"],
        ["true statement"] => ["tunay na saad"],
        ["truth set"] => ["tangkas ng katutohanan"],
    ],
    // Page 12
    [
        // 454-459
        ["union of two sets"] => ["kaisahan ng dalawang tangkas"],
        ["unit set"] => ["isahing tangkas"],
        ["universel set"] => ["lahatang tangkas"],
        ["variable"] => ["aligin"],
        ["Venn diagram"] => ["guhiting Venn"],
        ["well-defined set"] => ["ganap-turing na tangkas"],
    ],
);
