use crate::entries;

entries!(
    // Page 15
    [
        // 578-580
        ["acute angle"] => ["sihang kipot"],
        ["adjacent angles"] => ["sihang tabi"],
        ["adjacent sides"] => ["magkatabing gilid"],
        // 581-590
        ["alternate angles"] => ["sihang salisi"],
        ["altitude"] => ["tayog"],
        ["analytic geometry"] => ["suriing sukgisan"],
        ["angle"] => ["siha"],
        ["axiom"] => ["batlain"<e:"batayan na simulain">],
        ["base angle"] => ["sihang takaran"],
        ["broken line"] => ["guhit na bali-bali"],
        ["bulk"] => ["bikil"<l:MatTag>],
        ["centi-"] => ["senti-"],
        ["chord"] => ["bagting"],
        // 591-600
        ["coincident"] => ["magkatuntong", "katuntong"],
        ["collinear"] => ["magkaguhit", "kaguhit"],
        ["complementary angle"] => ["sihang kapuno"],
        ["conclusion"] => ["pasyahin"],
        ["confirmation"] => ["patutoo"],
        ["congruent"] => ["magkalapat", "kalapat"],
        ["construct a figure"] => ["gumuhit ng isang laraw"],
        ["construction"] => ["pagguhit"],
        ["corollary"] => ["hugpungin"],
        ["cube"<g:"solid Geo.">] => ["binuok"],
        // 601-609
        ["cube"<g:"the third power">] => ["talurami"],
        ["diagonal"] => ["hilis"],
        ["decagon"] => ["pulsiha"],
        ["decahedron"] => ["puldayah"],
        ["deci-"] => ["desi-"],
        ["degree"] => ["antas"],
        ["disc"] => ["dalipay"<l:MatTag>],
        ["draw a line"] => ["gumuhit"],
        ["ellipse"] => ["duyog"<l:MatTag>],
    ],
    // Page 16
    [
        // 610
        ["end point"] => ["dulong tuldok"],
        // 611-620
        ["equiangular"] => ["parisiha"],
        ["equilateral"<q:adj>] => ["parigilid"],
        ["evolute"] => ["balisultag"],
        ["foot"] => ["talampakan"],
        ["frame"] => ["bastagan"],
        ["French curve"] => ["kiluang galod"],
        ["fundamental principle"] => ["batayang simulain"],
        ["geometrical interpretation"] => ["sukgising pakahulugan"],
        ["geometry"] => ["sukgisan"<e:"sukat" "hugis" "-an">],
        ["globe"] => ["hilihid"<l:MatTag>],
        // 621-630
        ["helix"] => ["pilipit"],
        ["hemisphere"] => ["hatimbulog"],
        ["heptagon"] => ["pitsiha"],
        ["hypotenuse"] => ["gilis"<e:"gilid na hilis">],
        ["hexagon"] => ["nimsiha"],
        ["hexahedron"] => ["nimdayag"],
        ["hypothesis"] => ["palagayin"],
        ["inch"] => ["dali"],
        ["included angle"] => ["sihang ipit"],
        ["involute"] => ["sultag"<e:"sulong" "latag">],
        // 631-640
        ["isolated point"] => ["bukod na tuldok"],
        ["length"] => ["haba"],
        ["length of a segment"] => ["haba ng putol"],
        ["meter"] => ["metro"],
        ["midpoint"] => ["gituldok"],
        ["mid-section"] => ["gitapyas"],
        ["milli-"] => ["mili-"],
        ["nonagon"] => ["samsiha"],
        ["oblique"] => ["talibas"],
        ["oblique angle"] => ["sihang talibas"],
        // 641-650
        ["obtuse angle"] => ["sihang bika"],
        ["octagon"] => ["walsiha"],
        ["one dimensional figure"] => ["laraw na iisahing sukod"],
        ["opposite angle"] => ["sihang tapat"],
        ["oval"] => ["habilog"<e:"habang bilog">],
        ["parallel"] => ["agapay"],
        ["parallel lines"] => ["mga guhit na agapay"],
        ["parallelogram"] => ["parigapay"],
        ["parallel sections"] => ["mga tapyas na agapay"],
        ["perimeter"] => ["gikop"<e:"gilid" "salikop">],
    ],
    // Page 17
    [
        // 651-660
        ["pentahedron"] => ["limdayag"],
        ["pentagon"] => ["limsiha"],
        ["perpendicular"] => ["tadlong"],
        ["perspective"<g:"3-dimensional effect">] => ["sawang"<l:MatTag>],
        ["plane geometry"] => ["lapyang sukgisan"],
        ["principle"] => ["simulain"],
        ["proof"] => ["patunay"],
        ["protractor"] => ["paniha"],
        ["point-slope form"] => ["tuldok-hilig na anyo"],
        ["postulate"] => ["batayang palagay"],
        // 661-670
        ["premise"] => ["kahunaan"],
        ["prism"] => ["balimbing"],
        ["prolongation of a line"] => ["padayon ng guhit"],
        ["polygon"] => ["damsiha"],
        ["polyhedron"] => ["damdayag"<e:"dami" "hayag">],
        ["pyramid"] => ["tagilo"],
        ["quadrilateral"] => ["patgilid"],
        ["radius"] => ["lihit"],
        ["ray"] => ["sinag"],
        ["rectangle"] => ["paritadlong"],
        // 671-680
        ["rpesentation of a point"] => ["talihalat ng tuldok"],
        ["right angle"] => ["sihang tadlong"],
        ["rhomboid"] => ["tagihilis"],
        ["rhombus"] => ["tagisukat"],
        ["scale"<g:"of degrees">] => ["talaantasan"],
        ["secant"<g:"Geometry">] => ["tangab"<l:MatTag>],
        ["section"] => ["tapyas"],
        ["segment"] => ["putol"],
        ["segment"<g:"of a circle">] => ["liha"<g:"liha ng isang bilog">],
        ["semicircumference"] => ["hatintikop"],
        // 681-690
        ["shape"] => ["hugis"],
        ["slope"] => ["hilig"],
        ["solid geometry"] => ["siksing sukgisan"],
        ["spherical"] => ["timbulugin"],
        ["spherical geometry"] => ["timbuluging sukgisan"],
        ["spiral"] => ["balukay"],
        ["square"] => ["parisukat"],
        ["straight angle"] => ["sihang ladlad"],
        ["subsurface"] => ["kubdayag"],
        ["supplementary angle"] => ["sihang kaladlad"],
        // 691
        ["surface"] => ["dayag"],
    ],
    // Page 18
    [
        // 692-700
        ["surface"<g:"as contrasted to the reverse side">] => ["karayagan"],
        ["tangent"<g:"line">] => ["dikit"],
        ["theorem"] => ["hunain"],
        ["theory"] => ["huna"],
        ["tetrahedron"] => ["patdayag"],
        ["T-square"] => ["paripang galod"],
        ["trapezoid"] => ["tagigapay"<e:"tagibang" "agapay">],
        ["truncated"] => ["tinapyas"],
        ["two-dimensional figure"] => ["laraw na dadalawahing sukod"],
        // 701-705
        ["vertex angle"] => ["siha ng bagtasan"],
        ["vertex of an angle"] => ["bagtasan ng siha"],
        ["vertical axis"] => ["tayong taluhog"],
        ["width"] => ["lapad"],
        ["yard"] => ["yarda"],
    ],
);
